// This file is autogenerated by generate-ast.ts. DO NOT EDIT THIS FILE DIRECTLY.

export type Expr =
  | { tag: 'Literal'; value: boolean | number | string }
  | { tag: 'BigIntLiteral'; value: string }
  | { tag: 'Complex'; value: string }
  | { tag: 'Variable'; name: string }
  | { tag: 'Binary'; left: Expr; op: string; right: Expr }
  | { tag: 'Compare'; left: Expr; op: string; right: Expr }
  | { tag: 'BoolOp'; left: Expr; op: string; right: Expr }
  | { tag: 'Unary'; op: string; arg: Expr }
  | { tag: 'Ternary'; test: Expr; cons: Expr; alt: Expr }
  | { tag: 'Lambda'; params: string[]; body: Expr }
  | { tag: 'MultiLambda'; params: string[]; body: Stmt[] }
  | { tag: 'Call'; callee: Expr; args: Expr[] }
  | { tag: 'Group'; expr: Expr }
  | { tag: 'None' };

// ============================================================================
// Statements
// ============================================================================

export type Stmt =
  | { tag: 'Pass' }
  | { tag: 'Break' }
  | { tag: 'Continue' }
  | { tag: 'Return'; value: Expr | null }
  | { tag: 'Assign'; name: string; value: Expr }
  | { tag: 'AnnAssign'; name: string; ann: Expr; value: Expr | null }
  | { tag: 'Expr'; expr: Expr }
  | { tag: 'If'; test: Expr; body: Stmt[]; else: Stmt[] | null }
  | { tag: 'While'; test: Expr; body: Stmt[] }
  | { tag: 'For'; target: string; iter: Expr; body: Stmt[] }
  | { tag: 'FunctionDef'; name: string; params: string[]; body: Stmt[] }
  | { tag: 'FromImport'; module: string; names: string[] }
  | { tag: 'Global'; name: string }
  | { tag: 'NonLocal'; name: string }
  | { tag: 'Assert'; test: Expr }
  | { tag: 'File'; stmts: Stmt[] };

// ============================================================================
// Exhaustiveness helper
// ============================================================================

export function assertNever(x: never): never {
  throw new Error(`Unexpected: ${JSON.stringify(x)}`);
}
