import { readdir, writeFile } from "node:fs/promises";

/**
 * This script generates autocomplete data for built-in functions and variables
 *  by parsing raw JSDoc ASTs in `src/conductor/plugins/autocomplete/builtins`.
 * It assumes that the JSDoc ASTs are already generated by running `jsdoc -X` on the built-in JavaScript files.
 *
 * In most circumstances, you should not need to run this script manually,
 *  as it is automatically invoked by the `build` script in `package.json`.
 * If you want to regenerate the autocomplete data, you can run `./scripts/autocomplete.sh`,
 *  which will first regenerate the JSDoc ASTs and then run this script to generate the autocomplete data.
 *
 * It outputs JSON files containing the name, title, description, and meta information for each function and variable,
 * which are then used by the autocomplete plugin.
 *
 * Note: This script may not have all the type information for the built-ins. Feel free to edit the Entry type and the mapping logic to include more information if needed.
 */

type Entry =
  | {
      comment: string;
      description: string;
      params: {
        type: {
          names: string[];
        };
        description: string;
        name: string;
      }[];
      returns?: {
        type: {
          names: string[];
        };
        description: string;
      }[];
      name: string;
      longname: string;
      kind: "function";
      scope: string;
    }
  | {
      kind: "package";
      longname: string;
      files: string[];
    }
  | {
      comment: string;
      description: string;
      type: {
        names: string[];
      };
      name: string;
      longname: string;
      kind: "constant";
      scope: string;
    };

/**
 * The generation process is as follows:
 * 1. Find all the JSON files in the builtins directory, which are generated by running `jsdoc -X` on the built-in JavaScript files.
 * 2. For each JSON file, create a promise which
 *     a. Reads the JSON file and parses it into an array of Entry objects.
 *     b. Filters the entries to only include functions and constants, and maps them to a simplified format containing the name, title, description, and meta information.
 *     c. Writes the simplified entries back to the same JSON file, overwriting the original JSDoc AST.
 * 3. Wait for all the promises to complete before exiting the script.
 */
(async () => {
  return Promise.all(
    (await readdir("src/conductor/plugins/autocomplete/builtins"))
      .filter(file => file.endsWith(".json"))
      .map(async file => {
        const data = (await import(`./conductor/plugins/autocomplete/builtins/${file}`, {
          with: { type: "json" },
        })) as {
          default: Entry[];
        };
        await writeFile(
          `src/conductor/plugins/autocomplete/builtins/${file}`,
          JSON.stringify(
            data.default
              .filter(entry => entry.kind === "function" || entry.kind === "constant")
              .filter(entry => entry.scope === "global") // Only include global variables and functions in autocomplete suggestions
              .map(entry =>
                entry.kind === "function"
                  ? {
                      name: entry.name,
                      title:
                        entry.name +
                        "(" +
                        entry.params.map(p => p.name).join(", ") +
                        ") -> " +
                        (entry.returns?.[0].type.names[0] || "None"),
                      description: entry.description,
                      meta: "func",
                    }
                  : {
                      name: entry.name,
                      title: entry.name,
                      description: entry.description,
                      meta: "var",
                    },
              ),
          ),
        );
      }),
  );
})();
