import { CompletionItemKind } from "@sourceacademy/common-autocomplete";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const BUILTINS_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  "conductor/plugins/autocomplete/builtins",
);

/**
 * This script generates autocomplete data for built-in functions and variables
 *  by parsing raw JSDoc ASTs in `src/conductor/plugins/autocomplete/builtins`.
 * It assumes that the JSDoc ASTs are already generated by running `jsdoc -X` on the built-in JavaScript files.
 *
 * In most circumstances, you should not need to run this script manually,
 *  as it is automatically invoked by the `build` script in `package.json`.
 * If you want to regenerate the autocomplete data, you can run `./scripts/autocomplete.sh`,
 *  which will first regenerate the JSDoc ASTs and then run this script to generate the autocomplete data.
 *
 * It outputs JSON files containing the name, title, description, and meta information for each function and variable,
 * which are then used by the autocomplete plugin.
 *
 * Note: This script may not have all the type information for the built-ins. Feel free to edit the Entry type and the mapping logic to include more information if needed.
 */

type Entry =
  | {
      comment: string;
      description: string;
      params: {
        type: {
          names: string[];
        };
        description: string;
        name: string;
      }[];
      returns?: {
        // JSDoc omits `type` when `@returns` has only a description, no type annotation.
        type?: {
          names: string[];
        };
        description: string;
      }[];
      name: string;
      longname: string;
      kind: "function";
      scope: string;
    }
  | {
      kind: "package";
      longname: string;
      files: string[];
    }
  | {
      comment: string;
      description: string;
      type: {
        names: string[];
      };
      name: string;
      longname: string;
      kind: "constant";
      scope: string;
    };

type TransformedEntry = {
  name: string;
  title: string;
  description: string;
  meta: CompletionItemKind;
};

/**
 * The generation process is as follows:
 * 1. Find all the JSON files in the builtins directory, which are generated by running `jsdoc -X` on the built-in JavaScript files.
 * 2. For each JSON file, create a promise which
 *     a. Reads the JSON file and parses it into an array of Entry objects.
 *     b. Filters the entries to only include functions and constants, and maps them to a simplified format containing the name, title, description, and meta information.
 *     c. Writes the simplified entries back to the same JSON file, overwriting the original JSDoc AST.
 * 3. Wait for all the promises to complete before exiting the script.
 *
 * Reads/writes are anchored to this module's own location (not process.cwd()) so the script
 * works regardless of the directory it's invoked from. Files that have already been transformed
 * (no "kind" field left) are left alone, so re-running the script - e.g. a second `yarn build` -
 * is a no-op instead of filtering everything out and silently overwriting the file with `[]`.
 */
(async () => {
  await Promise.all(
    (await readdir(BUILTINS_DIR))
      .filter(file => file.endsWith(".json"))
      .map(async file => {
        const path = join(BUILTINS_DIR, file);
        const entries = JSON.parse(await readFile(path, "utf8")) as Entry[] | TransformedEntry[];
        if (!entries.some(entry => "kind" in entry)) {
          return;
        }
        await writeFile(
          path,
          JSON.stringify(
            (entries as Entry[])
              .filter(entry => entry.kind === "function" || entry.kind === "constant")
              .filter(entry => entry.scope === "global") // Only include global variables and functions in autocomplete suggestions
              .map(
                (entry): TransformedEntry =>
                  entry.kind === "function"
                    ? {
                        name: entry.name,
                        title:
                          entry.name +
                          "(" +
                          entry.params.map(p => p.name).join(", ") +
                          ") -> " +
                          (entry.returns?.[0]?.type?.names?.[0] ?? "None"),
                        description: entry.description,
                        meta: CompletionItemKind.Function,
                      }
                    : {
                        name: entry.name,
                        title: entry.name,
                        description: entry.description,
                        meta: CompletionItemKind.Variable,
                      },
              ),
          ),
        );
      }),
  );
})().catch(error => {
  console.error(error);
  process.exit(1);
});
